import 'package:money_flow/features/settings/data/models/currency_model.dart';

class AppCurrencies {
  static const currencies = [
    // Africa
    CurrencyModel(
      code: 'DZD',
      name: 'Algerian Dinar',
      symbol: 'دج',
      flag: '🇩🇿',
    ),
    CurrencyModel(
      code: 'AOA',
      name: 'Angolan Kwanza',
      symbol: 'Kz',
      flag: '🇦🇴',
    ),
    CurrencyModel(
      code: 'BWP',
      name: 'Botswana Pula',
      symbol: 'P',
      flag: '🇧🇼',
    ),
    CurrencyModel(
      code: 'BIF',
      name: 'Burundian Franc',
      symbol: 'FBu',
      flag: '🇧🇮',
    ),
    CurrencyModel(
      code: 'CVE',
      name: 'Cape Verdean Escudo',
      symbol: '\$',
      flag: '🇨🇻',
    ),
    CurrencyModel(
      code: 'XAF',
      name: 'Central African CFA Franc',
      symbol: 'FCFA',
      flag: '🌍',
    ),
    CurrencyModel(
      code: 'KMF',
      name: 'Comorian Franc',
      symbol: 'CF',
      flag: '🇰🇲',
    ),
    CurrencyModel(
      code: 'CDF',
      name: 'Congolese Franc',
      symbol: 'FC',
      flag: '🇨🇩',
    ),
    CurrencyModel(
      code: 'DJF',
      name: 'Djiboutian Franc',
      symbol: 'Fdj',
      flag: '🇩🇯',
    ),
    CurrencyModel(
      code: 'EGP',
      name: 'Egyptian Pound',
      symbol: 'E£',
      flag: '🇪🇬',
    ),
    CurrencyModel(
      code: 'ERN',
      name: 'Eritrean Nakfa',
      symbol: 'Nfk',
      flag: '🇪🇷',
    ),
    CurrencyModel(
      code: 'SZL',
      name: 'Eswatini Lilangeni',
      symbol: 'E',
      flag: '🇸🇿',
    ),
    CurrencyModel(
      code: 'ETB',
      name: 'Ethiopian Birr',
      symbol: 'Br',
      flag: '🇪🇹',
    ),
    CurrencyModel(
      code: 'GMD',
      name: 'Gambian Dalasi',
      symbol: 'D',
      flag: '🇬🇲',
    ),
    CurrencyModel(
      code: 'GHS',
      name: 'Ghanaian Cedi',
      symbol: '₵',
      flag: '🇬🇭',
    ),
    CurrencyModel(
      code: 'GNF',
      name: 'Guinean Franc',
      symbol: 'FG',
      flag: '🇬🇳',
    ),
    CurrencyModel(
      code: 'KES',
      name: 'Kenyan Shilling',
      symbol: 'KSh',
      flag: '🇰🇪',
    ),
    CurrencyModel(code: 'LSL', name: 'Lesotho Loti', symbol: 'L', flag: '🇱🇸'),
    CurrencyModel(
      code: 'LRD',
      name: 'Liberian Dollar',
      symbol: 'L\$',
      flag: '🇱🇷',
    ),
    CurrencyModel(
      code: 'LYD',
      name: 'Libyan Dinar',
      symbol: 'ل.د',
      flag: '🇱🇾',
    ),
    CurrencyModel(
      code: 'MGA',
      name: 'Malagasy Ariary',
      symbol: 'Ar',
      flag: '🇲🇬',
    ),
    CurrencyModel(
      code: 'MWK',
      name: 'Malawian Kwacha',
      symbol: 'MK',
      flag: '🇲🇼',
    ),
    CurrencyModel(
      code: 'MRU',
      name: 'Mauritanian Ouguiya',
      symbol: 'UM',
      flag: '🇲🇷',
    ),
    CurrencyModel(
      code: 'MUR',
      name: 'Mauritian Rupee',
      symbol: '₨',
      flag: '🇲🇺',
    ),
    CurrencyModel(
      code: 'MAD',
      name: 'Moroccan Dirham',
      symbol: 'د.م.',
      flag: '🇲🇦',
    ),
    CurrencyModel(
      code: 'MZN',
      name: 'Mozambican Metical',
      symbol: 'MT',
      flag: '🇲🇿',
    ),
    CurrencyModel(
      code: 'NAD',
      name: 'Namibian Dollar',
      symbol: 'N\$',
      flag: '🇳🇦',
    ),
    CurrencyModel(
      code: 'NGN',
      name: 'Nigerian Naira',
      symbol: '₦',
      flag: '🇳🇬',
    ),
    CurrencyModel(
      code: 'RWF',
      name: 'Rwandan Franc',
      symbol: 'FRw',
      flag: '🇷🇼',
    ),
    CurrencyModel(
      code: 'STN',
      name: 'São Tomé and Príncipe Dobra',
      symbol: 'Db',
      flag: '🇸🇹',
    ),
    CurrencyModel(
      code: 'SCR',
      name: 'Seychellois Rupee',
      symbol: '₨',
      flag: '🇸🇨',
    ),
    CurrencyModel(
      code: 'SLL',
      name: 'Sierra Leonean Leone',
      symbol: 'Le',
      flag: '🇸🇱',
    ),
    CurrencyModel(
      code: 'SOS',
      name: 'Somali Shilling',
      symbol: 'Sh',
      flag: '🇸🇴',
    ),
    CurrencyModel(
      code: 'ZAR',
      name: 'South African Rand',
      symbol: 'R',
      flag: '🇿🇦',
    ),
    CurrencyModel(
      code: 'SSP',
      name: 'South Sudanese Pound',
      symbol: '£',
      flag: '🇸🇸',
    ),
    CurrencyModel(
      code: 'SDG',
      name: 'Sudanese Pound',
      symbol: 'ج.س.',
      flag: '🇸🇩',
    ),
    CurrencyModel(
      code: 'TZS',
      name: 'Tanzanian Shilling',
      symbol: 'TSh',
      flag: '🇹🇿',
    ),
    CurrencyModel(
      code: 'TND',
      name: 'Tunisian Dinar',
      symbol: 'د.ت',
      flag: '🇹🇳',
    ),
    CurrencyModel(
      code: 'UGX',
      name: 'Ugandan Shilling',
      symbol: 'USh',
      flag: '🇺🇬',
    ),
    CurrencyModel(
      code: 'ZMW',
      name: 'Zambian Kwacha',
      symbol: 'ZK',
      flag: '🇿🇲',
    ),
    CurrencyModel(
      code: 'ZWL',
      name: 'Zimbabwean Dollar',
      symbol: 'Z\$',
      flag: '🇿🇼',
    ),

    // Americas
    CurrencyModel(code: 'USD', name: 'US Dollar', symbol: '\$', flag: '🇺🇸'),
    CurrencyModel(
      code: 'CAD',
      name: 'Canadian Dollar',
      symbol: 'C\$',
      flag: '🇨🇦',
    ),
    CurrencyModel(
      code: 'MXN',
      name: 'Mexican Peso',
      symbol: '\$',
      flag: '🇲🇽',
    ),
    CurrencyModel(
      code: 'BRL',
      name: 'Brazilian Real',
      symbol: 'R\$',
      flag: '🇧🇷',
    ),
    CurrencyModel(
      code: 'ARS',
      name: 'Argentine Peso',
      symbol: '\$',
      flag: '🇦🇷',
    ),
    CurrencyModel(
      code: 'CLP',
      name: 'Chilean Peso',
      symbol: '\$',
      flag: '🇨🇱',
    ),
    CurrencyModel(
      code: 'COP',
      name: 'Colombian Peso',
      symbol: '\$',
      flag: '🇨🇴',
    ),
    CurrencyModel(
      code: 'PEN',
      name: 'Peruvian Sol',
      symbol: 'S/',
      flag: '🇵🇪',
    ),
    CurrencyModel(
      code: 'UYU',
      name: 'Uruguayan Peso',
      symbol: '\$',
      flag: '🇺🇾',
    ),
    CurrencyModel(
      code: 'PYG',
      name: 'Paraguayan Guaraní',
      symbol: '₲',
      flag: '🇵🇾',
    ),
    CurrencyModel(
      code: 'BOB',
      name: 'Bolivian Boliviano',
      symbol: 'Bs.',
      flag: '🇧🇴',
    ),
    CurrencyModel(
      code: 'VES',
      name: 'Venezuelan Bolívar',
      symbol: 'Bs.',
      flag: '🇻🇪',
    ),
    CurrencyModel(
      code: 'CRC',
      name: 'Costa Rican Colón',
      symbol: '₡',
      flag: '🇨🇷',
    ),
    CurrencyModel(
      code: 'GTQ',
      name: 'Guatemalan Quetzal',
      symbol: 'Q',
      flag: '🇬🇹',
    ),
    CurrencyModel(
      code: 'HNL',
      name: 'Honduran Lempira',
      symbol: 'L',
      flag: '🇭🇳',
    ),
    CurrencyModel(
      code: 'NIO',
      name: 'Nicaraguan Córdoba',
      symbol: 'C\$',
      flag: '🇳🇮',
    ),
    CurrencyModel(
      code: 'PAB',
      name: 'Panamanian Balboa',
      symbol: 'B/.',
      flag: '🇵🇦',
    ),
    CurrencyModel(
      code: 'DOP',
      name: 'Dominican Peso',
      symbol: 'RD\$',
      flag: '🇩🇴',
    ),
    CurrencyModel(
      code: 'JMD',
      name: 'Jamaican Dollar',
      symbol: 'J\$',
      flag: '🇯🇲',
    ),
    CurrencyModel(
      code: 'TTD',
      name: 'Trinidad and Tobago Dollar',
      symbol: 'TT\$',
      flag: '🇹🇹',
    ),
    CurrencyModel(
      code: 'BBD',
      name: 'Barbadian Dollar',
      symbol: 'Bds\$',
      flag: '🇧🇧',
    ),
    CurrencyModel(
      code: 'BSD',
      name: 'Bahamian Dollar',
      symbol: 'B\$',
      flag: '🇧🇸',
    ),
    CurrencyModel(
      code: 'BZD',
      name: 'Belize Dollar',
      symbol: 'BZ\$',
      flag: '🇧🇿',
    ),
    CurrencyModel(
      code: 'XCD',
      name: 'East Caribbean Dollar',
      symbol: 'EC\$',
      flag: '🌎',
    ),
    CurrencyModel(
      code: 'HTG',
      name: 'Haitian Gourde',
      symbol: 'G',
      flag: '🇭🇹',
    ),
    CurrencyModel(code: 'CUP', name: 'Cuban Peso', symbol: '\$', flag: '🇨🇺'),

    // Europe
    CurrencyModel(code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺'),
    CurrencyModel(
      code: 'GBP',
      name: 'British Pound',
      symbol: '£',
      flag: '🇬🇧',
    ),
    CurrencyModel(
      code: 'CHF',
      name: 'Swiss Franc',
      symbol: 'CHF',
      flag: '🇨🇭',
    ),
    CurrencyModel(
      code: 'NOK',
      name: 'Norwegian Krone',
      symbol: 'kr',
      flag: '🇳🇴',
    ),
    CurrencyModel(
      code: 'SEK',
      name: 'Swedish Krona',
      symbol: 'kr',
      flag: '🇸🇪',
    ),
    CurrencyModel(
      code: 'DKK',
      name: 'Danish Krone',
      symbol: 'kr',
      flag: '🇩🇰',
    ),
    CurrencyModel(
      code: 'ISK',
      name: 'Icelandic Króna',
      symbol: 'kr',
      flag: '🇮🇸',
    ),
    CurrencyModel(
      code: 'PLN',
      name: 'Polish Zloty',
      symbol: 'zł',
      flag: '🇵🇱',
    ),
    CurrencyModel(
      code: 'CZK',
      name: 'Czech Koruna',
      symbol: 'Kč',
      flag: '🇨🇿',
    ),
    CurrencyModel(
      code: 'HUF',
      name: 'Hungarian Forint',
      symbol: 'Ft',
      flag: '🇭🇺',
    ),
    CurrencyModel(
      code: 'RON',
      name: 'Romanian Leu',
      symbol: 'lei',
      flag: '🇷🇴',
    ),
    CurrencyModel(
      code: 'BGN',
      name: 'Bulgarian Lev',
      symbol: 'лв',
      flag: '🇧🇬',
    ),
    CurrencyModel(
      code: 'RSD',
      name: 'Serbian Dinar',
      symbol: 'дин.',
      flag: '🇷🇸',
    ),
    CurrencyModel(
      code: 'BAM',
      name: 'Bosnia-Herzegovina Mark',
      symbol: 'KM',
      flag: '🇧🇦',
    ),
    CurrencyModel(
      code: 'MKD',
      name: 'Macedonian Denar',
      symbol: 'ден',
      flag: '🇲🇰',
    ),
    CurrencyModel(
      code: 'ALL',
      name: 'Albanian Lek',
      symbol: 'Lek',
      flag: '🇦🇱',
    ),
    CurrencyModel(code: 'MDL', name: 'Moldovan Leu', symbol: 'L', flag: '🇲🇩'),
    CurrencyModel(
      code: 'UAH',
      name: 'Ukrainian Hryvnia',
      symbol: '₴',
      flag: '🇺🇦',
    ),
    CurrencyModel(
      code: 'GEL',
      name: 'Georgian Lari',
      symbol: '₾',
      flag: '🇬🇪',
    ),
    CurrencyModel(
      code: 'AMD',
      name: 'Armenian Dram',
      symbol: '֏',
      flag: '🇦🇲',
    ),
    CurrencyModel(
      code: 'AZN',
      name: 'Azerbaijani Manat',
      symbol: '₼',
      flag: '🇦🇿',
    ),
    CurrencyModel(
      code: 'BYN',
      name: 'Belarusian Ruble',
      symbol: 'Br',
      flag: '🇧🇾',
    ),
    CurrencyModel(
      code: 'RUB',
      name: 'Russian Ruble',
      symbol: '₽',
      flag: '🇷🇺',
    ),
    CurrencyModel(code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷'),

    // Middle East
    CurrencyModel(code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', flag: '🇸🇦'),
    CurrencyModel(code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪'),
    CurrencyModel(code: 'QAR', name: 'Qatari Riyal', symbol: '﷼', flag: '🇶🇦'),
    CurrencyModel(
      code: 'KWD',
      name: 'Kuwaiti Dinar',
      symbol: 'د.ك',
      flag: '🇰🇼',
    ),
    CurrencyModel(
      code: 'BHD',
      name: 'Bahraini Dinar',
      symbol: '.د.ب',
      flag: '🇧🇭',
    ),
    CurrencyModel(code: 'OMR', name: 'Omani Rial', symbol: '﷼', flag: '🇴🇲'),
    CurrencyModel(
      code: 'JOD',
      name: 'Jordanian Dinar',
      symbol: 'د.ا',
      flag: '🇯🇴',
    ),
    CurrencyModel(
      code: 'IQD',
      name: 'Iraqi Dinar',
      symbol: 'ع.د',
      flag: '🇮🇶',
    ),
    CurrencyModel(
      code: 'LBP',
      name: 'Lebanese Pound',
      symbol: 'ل.ل',
      flag: '🇱🇧',
    ),
    CurrencyModel(code: 'SYP', name: 'Syrian Pound', symbol: '£', flag: '🇸🇾'),

    CurrencyModel(code: 'YER', name: 'Yemeni Rial', symbol: '﷼', flag: '🇾🇪'),
    CurrencyModel(code: 'IRR', name: 'Iranian Rial', symbol: '﷼', flag: '🇮🇷'),

    // Asia
    CurrencyModel(code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵'),
    CurrencyModel(code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳'),
    CurrencyModel(code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳'),
    CurrencyModel(
      code: 'KRW',
      name: 'South Korean Won',
      symbol: '₩',
      flag: '🇰🇷',
    ),
    CurrencyModel(
      code: 'IDR',
      name: 'Indonesian Rupiah',
      symbol: 'Rp',
      flag: '🇮🇩',
    ),
    CurrencyModel(
      code: 'MYR',
      name: 'Malaysian Ringgit',
      symbol: 'RM',
      flag: '🇲🇾',
    ),
    CurrencyModel(
      code: 'SGD',
      name: 'Singapore Dollar',
      symbol: 'S\$',
      flag: '🇸🇬',
    ),
    CurrencyModel(code: 'THB', name: 'Thai Baht', symbol: '฿', flag: '🇹🇭'),
    CurrencyModel(
      code: 'PHP',
      name: 'Philippine Peso',
      symbol: '₱',
      flag: '🇵🇭',
    ),
    CurrencyModel(
      code: 'VND',
      name: 'Vietnamese Dong',
      symbol: '₫',
      flag: '🇻🇳',
    ),
    CurrencyModel(
      code: 'PKR',
      name: 'Pakistani Rupee',
      symbol: '₨',
      flag: '🇵🇰',
    ),
    CurrencyModel(
      code: 'BDT',
      name: 'Bangladeshi Taka',
      symbol: '৳',
      flag: '🇧🇩',
    ),
    CurrencyModel(
      code: 'LKR',
      name: 'Sri Lankan Rupee',
      symbol: 'Rs',
      flag: '🇱🇰',
    ),
    CurrencyModel(
      code: 'NPR',
      name: 'Nepalese Rupee',
      symbol: '₨',
      flag: '🇳🇵',
    ),
    CurrencyModel(
      code: 'AFN',
      name: 'Afghan Afghani',
      symbol: '؋',
      flag: '🇦🇫',
    ),
    CurrencyModel(
      code: 'MNT',
      name: 'Mongolian Tögrög',
      symbol: '₮',
      flag: '🇲🇳',
    ),
    CurrencyModel(
      code: 'KZT',
      name: 'Kazakhstani Tenge',
      symbol: '₸',
      flag: '🇰🇿',
    ),
    CurrencyModel(
      code: 'UZS',
      name: 'Uzbekistani Som',
      symbol: 'лв',
      flag: '🇺🇿',
    ),
    CurrencyModel(
      code: 'KGS',
      name: 'Kyrgyzstani Som',
      symbol: 'с',
      flag: '🇰🇬',
    ),
    CurrencyModel(
      code: 'TJS',
      name: 'Tajikistani Somoni',
      symbol: 'ЅМ',
      flag: '🇹🇯',
    ),
    CurrencyModel(
      code: 'TMT',
      name: 'Turkmenistani Manat',
      symbol: 'm',
      flag: '🇹🇲',
    ),
    CurrencyModel(code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', flag: '🇲🇲'),
    CurrencyModel(
      code: 'KHR',
      name: 'Cambodian Riel',
      symbol: '៛',
      flag: '🇰🇭',
    ),
    CurrencyModel(code: 'LAK', name: 'Lao Kip', symbol: '₭', flag: '🇱🇦'),
    CurrencyModel(
      code: 'BND',
      name: 'Brunei Dollar',
      symbol: 'B\$',
      flag: '🇧🇳',
    ),
    CurrencyModel(
      code: 'BTN',
      name: 'Bhutanese Ngultrum',
      symbol: 'Nu.',
      flag: '🇧🇹',
    ),
    CurrencyModel(
      code: 'MVR',
      name: 'Maldivian Rufiyaa',
      symbol: 'Rf',
      flag: '🇲🇻',
    ),
    CurrencyModel(
      code: 'FJD',
      name: 'Fijian Dollar',
      symbol: 'FJ\$',
      flag: '🇫🇯',
    ),

    // Oceania
    CurrencyModel(
      code: 'AUD',
      name: 'Australian Dollar',
      symbol: 'A\$',
      flag: '🇦🇺',
    ),
    CurrencyModel(
      code: 'NZD',
      name: 'New Zealand Dollar',
      symbol: 'NZ\$',
      flag: '🇳🇿',
    ),
    CurrencyModel(
      code: 'PGK',
      name: 'Papua New Guinean Kina',
      symbol: 'K',
      flag: '🇵🇬',
    ),
    CurrencyModel(
      code: 'WST',
      name: 'Samoan Tala',
      symbol: 'WS\$',
      flag: '🇼🇸',
    ),
    CurrencyModel(
      code: 'TOP',
      name: 'Tongan Paʻanga',
      symbol: 'T\$',
      flag: '🇹🇴',
    ),
    CurrencyModel(
      code: 'VUV',
      name: 'Vanuatu Vatu',
      symbol: 'VT',
      flag: '🇻🇺',
    ),
    CurrencyModel(
      code: 'SBD',
      name: 'Solomon Islands Dollar',
      symbol: 'SI\$',
      flag: '🇸🇧',
    ),
  ];
}
